# Dependencies
#
# gem 'jekyll'
# gem 'jekyll-paginate'

markdown: kramdown

kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Brandon Mathis
tagline: 'Few facts, mostly opinions.'
description: '<a href="http://brandonmathis.me" target="_blank">Brandon Mathis</a> is a Freelance Full-Stack developer living and working in Raleigh, NC. <br/> <a href="http://twitter.com/brandonmathis">@BrandonMathis</a>'
url: http://brandonmathis.me
baseurl: '/'

author:
  name: 'Brandon Mathis'
  url: https://twitter.com/brandonmathis

paginate: 1

plugins:
  - jekyll-paginate
