# Dependencies
#
# gem 'jekyll'
# gem 'jekyll-paginate'

markdown: kramdown

kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Brandon Mathis
tagline: 'Few facts, mostly opinions.'
description: 'Brandon Mathis is a Freelance Full-Stack developer living and working in Raleigh, NC.'
url: https://blog.brandonmathis.me/
baseurl: '/'

author:
  name: 'Brandon Mathis'
  url: https://twitter.com/brandonmathis

paginate: 1

plugins:
  - jekyll-paginate
